
name: mysql
services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./database-scripts:/database-scripts
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

